// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Faroukhamadi/Banketeer/teller_service/tellerdb/ent/schema"
	"github.com/Faroukhamadi/Banketeer/teller_service/tellerdb/ent/teller"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tellerMixin := schema.Teller{}.Mixin()
	tellerMixinFields0 := tellerMixin[0].Fields()
	_ = tellerMixinFields0
	tellerFields := schema.Teller{}.Fields()
	_ = tellerFields
	// tellerDescCreateTime is the schema descriptor for create_time field.
	tellerDescCreateTime := tellerMixinFields0[0].Descriptor()
	// teller.DefaultCreateTime holds the default value on creation for the create_time field.
	teller.DefaultCreateTime = tellerDescCreateTime.Default.(func() time.Time)
	// tellerDescUpdateTime is the schema descriptor for update_time field.
	tellerDescUpdateTime := tellerMixinFields0[1].Descriptor()
	// teller.DefaultUpdateTime holds the default value on creation for the update_time field.
	teller.DefaultUpdateTime = tellerDescUpdateTime.Default.(func() time.Time)
	// teller.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	teller.UpdateDefaultUpdateTime = tellerDescUpdateTime.UpdateDefault.(func() time.Time)
}
