// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TellersColumns holds the columns for the "tellers" table.
	TellersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"customer", "admin"}, Default: "customer"},
	}
	// TellersTable holds the schema information for the "tellers" table.
	TellersTable = &schema.Table{
		Name:       "tellers",
		Columns:    TellersColumns,
		PrimaryKey: []*schema.Column{TellersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TellersTable,
	}
)

func init() {
}
