// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Faroukhamadi/Banketeer/transaction_service/transactiondb/ent/transaction"
)

// Transaction is the model entity for the Transaction schema.
type Transaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// AccountId holds the value of the "accountId" field.
	AccountId int `json:"accountId,omitempty"`
	// SenderAccountId holds the value of the "senderAccountId" field.
	SenderAccountId int `json:"senderAccountId,omitempty"`
	// ReceiverAccountId holds the value of the "receiverAccountId" field.
	ReceiverAccountId int `json:"receiverAccountId,omitempty"`
	// TellerId holds the value of the "tellerId" field.
	TellerId int `json:"tellerId,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Transaction) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID, transaction.FieldAccountId, transaction.FieldSenderAccountId, transaction.FieldReceiverAccountId, transaction.FieldTellerId:
			values[i] = new(sql.NullInt64)
		case transaction.FieldCreateTime, transaction.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Transaction", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Transaction fields.
func (t *Transaction) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case transaction.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				t.CreateTime = value.Time
			}
		case transaction.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				t.UpdateTime = value.Time
			}
		case transaction.FieldAccountId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accountId", values[i])
			} else if value.Valid {
				t.AccountId = int(value.Int64)
			}
		case transaction.FieldSenderAccountId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field senderAccountId", values[i])
			} else if value.Valid {
				t.SenderAccountId = int(value.Int64)
			}
		case transaction.FieldReceiverAccountId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field receiverAccountId", values[i])
			} else if value.Valid {
				t.ReceiverAccountId = int(value.Int64)
			}
		case transaction.FieldTellerId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tellerId", values[i])
			} else if value.Valid {
				t.TellerId = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Transaction.
// Note that you need to call Transaction.Unwrap() before calling this method if this Transaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Transaction) Update() *TransactionUpdateOne {
	return (&TransactionClient{config: t.config}).UpdateOne(t)
}

// Unwrap unwraps the Transaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Transaction) Unwrap() *Transaction {
	tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Transaction is not a transactional entity")
	}
	t.config.driver = tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Transaction) String() string {
	var builder strings.Builder
	builder.WriteString("Transaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("create_time=")
	builder.WriteString(t.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(t.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("accountId=")
	builder.WriteString(fmt.Sprintf("%v", t.AccountId))
	builder.WriteString(", ")
	builder.WriteString("senderAccountId=")
	builder.WriteString(fmt.Sprintf("%v", t.SenderAccountId))
	builder.WriteString(", ")
	builder.WriteString("receiverAccountId=")
	builder.WriteString(fmt.Sprintf("%v", t.ReceiverAccountId))
	builder.WriteString(", ")
	builder.WriteString("tellerId=")
	builder.WriteString(fmt.Sprintf("%v", t.TellerId))
	builder.WriteByte(')')
	return builder.String()
}

// Transactions is a parsable slice of Transaction.
type Transactions []*Transaction

func (t Transactions) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
